#!/usr/bin/env -S docker stack deploy --with-registry-auth httpbin -c

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml httpbin

services:
  httpbin:
    image: ghcr.io/zerocluster/httpbin
    # depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      labels:
        nginx: upstream=80&server=80,443&serverName=httpbin.softvisio.net&cacheEnabled=true&cacheBypass=true

    command: run

    # secrets:
    #   - { source: httpbin, target: /var/local/package/env.yaml }

    networks: [network]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }

    build: .

# secrets:
#   httpbin: { file: env.production.local.yaml }

networks:
  network:
    name: ${DOCKER_STACK_NETWORK_NAME:-main}
    external: true
